name: Feature request
description: Suggest an idea for this project
title: ''
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **Is your feature request related to a problem? Please describe.**
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.
      placeholder: Describe the problem here
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Describe the solution you'd like**
        A clear and concise description of what you want to happen.
  - type: textarea
    id: solution-description
    attributes:
      label: Solution Description
      description: A clear and concise description of what you want to happen.
      placeholder: Describe the solution here
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **Describe alternatives you've considered**
        A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: alternatives-description
    attributes:
      label: Alternatives Description
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: Describe alternatives here
  - type: markdown
    attributes:
      value: |
        **Additional context**
        Add any other context or screenshots about the feature request here.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Add any other context here
